name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch tout l'historique pour récupérer correctement les dates de modification

      - name: Restore file timestamps based on Git
        run: |
          git ls-tree -r --name-only HEAD | while read filename; do
            # Récupère la dernière date de modification pour chaque fichier et la restaure
            touch -d "$(git log -1 --format=%ci -- "$filename")" "$filename"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          preserveTimestamps: true  # Conserve les timestamps restaurés

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
