name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupère tout l'historique Git

      - name: Inject lastUpdated metadata into Markdown files
        run: |
          for file in $(find . -type f -name '*.md'); do
            # Récupère la dernière date de modification du fichier
            last_modified=$(git log -1 --format=%ci -- "$file")
            # Vérifie si le fichier a déjà une métadonnée lastUpdated
            if grep -q "^lastUpdated:" "$file"; then
              # Mets à jour la métadonnée existante
              sed -i "s/^lastUpdated: .*/lastUpdated: $last_modified/" "$file"
            else
              # Ajoute la métadonnée en haut du fichier
              sed -i "1s/^/---\nlastUpdated: $last_modified\n---\n/" "$file"
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          preserveTimestamps: true  # Conserve les timestamps pour cohérence

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
