name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupère tout l'historique pour extraire les dates

      - name: Inject last modified date into files
        run: |
          for file in $(find . -type f -name '*.md'); do
            # Récupérer la dernière date de modification de chaque fichier
            last_modified=$(git log -1 --format=%ci -- "$file")
            # Ajouter la date en haut du fichier Markdown
            sed -i "1s/^/<!-- Last modified: $last_modified -->\n/" "$file"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          preserveTimestamps: true  # Conserver les timestamps

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
